### ISSUE TITLE
When product is not found, display add product form

### ISSUE THREAD

**Issue by rlaferla** [okfn/labs-opd#19]
When a user enters a valid GTIN-13 code but the product is not in the database, display a form so that the user can manually enter the product data.  This data can be tagged "unverified" if necessary and possible with other metadata such as the user who entered it, the date created, etc...   This would be enormously useful as it would help improve the number of products in the database.

**Comment by avdata99** [comment]
This repository has been archived due to inactivity. See #16 for alternatives
