### ISSUE TITLE
Issues remaining

### ISSUE THREAD

**Issue by danfowler** [okfn/labs-opd#2]
To be split out into proper issues:
- [ ] currently debug = true (unset for production) 
- [ ] manage static files on production (put everything on Amazon S3)
- [ ] remove database dump from GitHub
- [ ] the top bar must be adapted be connected with http://product-data.okfnlabs.org
- [ ] download section ( http://labs-opd.herokuapp.com/download ): files to download must be stored somewhere (currently stored on the lab server (http://www.product-open-data.com/download/)
- [ ] the url http://www.product-open-data.com should be replaced by http://product-data.okfnlabs.org/browser/

**Comment by avdata99** [comment]
This repository has been archived due to inactivity. See #16 for alternatives
