### ISSUE TITLE
Debug mode is on

### ISSUE THREAD

**Issue by urszulasologub** [okfn/labs-opd#26]
Guys, your project looks really great and I am so glad I found it, but I think you've got a serious security issue: the debug mode is on.
Also, I tried to use your search input with data "50001125576642", but it showed me a full error stack. Please, turn off the debug mode, so any user won't see any sensitive data anymore
![image](https://user-images.githubusercontent.com/34507753/145719122-f7130afc-9308-441c-9512-51f965c2a977.png)

**Comment by amercader** [comment]
Thanks @urszulasologub. You are absolutely right. 

This project has been abandoned for so long though that we can't redeploy it without some extra work. We will more likely shut it down in the near future. 
I recommend looking at alternatives mentioned here: https://github.com/okfn/labs-opd/issues/16

**Comment by avdata99** [comment]
This repository has been archived due to inactivity. See #16 for alternatives
