### ISSUE TITLE
Data download links dead 

### ISSUE THREAD

**Issue by JoshSong** [okfn/labs-opd#5]
The links on http://product-open-data.com/download seem to be dead

**Comment by kenorb** [comment]
Try the archived version: https://web.archive.org/web/20171227230516/http://www.product-open-data.com:80/download

Some links still works.

**Comment by kenorb** [comment]
Found some files here: https://pod.opendatasoft.com/explore/

**Comment by JoshSong** [comment]
Wow thanks! Your second link had the data I was after.

**Comment by pwalsh** [comment]
Hi!

This site was moved from a dedicated server to Heroku a year or so ago, and as far as I can tell that is when we lost the download files. If anyone has those files, we can get them up on an S3 bucket or something, and update the links.

**Comment by kenorb** [comment]
Which files were lost and are still missing? As far as I can see, most of them can be downloaded from: https://pod.opendatasoft.com/explore/

Most of the brand images (~4G) are still being downloadable from S3 based on the links from `pod_gtin.csv` file (unfortunately not all of them). E.g.

```
rg -o "http?://[^;]+" pod_gtin.csv > images.txt
wget -c -x -nH -i images.txt
```

**Comment by Rik44444** [comment]
hi all, i'm interested in trying to pick up the goal of developing a database of product data that can be accessed by everyone - it would be good to build from existing or past initiatives in the field. I've been able to download all files here: https://web.archive.org/web/20170624020313/http://product-open-data.com/docs/pod_pictures_gtin_2013.08.29_01.zip 
except the 2.6 gb pictures file, which seems corrupted. Does anyone have this file?
More broadly it would be good to be in touch with the people who worked on Product Open Data, so if you're out there, please send me a message!

**Comment by johanricher** [comment]
How about joining hands with [OpenFoodFacts](https://openfoodfacts.org), a crowdsourced initiave which has been very successful in recent years? and expand it to Open _Product_ Facts which is the goal they have set themselves (see [this 2018 article](https://en.blog.openfoodfacts.org/news/introducing-open-products-facts-all-your-product-are-belong-to-us)). They're very open to outside ideas and contributions, for example as part of the Google Summer of Code and stuff like that.

Wikidata would also be a good option -- in fact anything would be better that starting yet another project IMHO. :wink:

**Comment by Rik44444** [comment]
> 
> 
> How about joining hands with [OpenFoodFacts](https://openfoodfacts.org), a crowdsourced initiave which has been very successful in recent years? and expand it to Open _Product_ Facts which is the goal they have set themselves (see [this 2018 article](https://en.blog.openfoodfacts.org/news/introducing-open-products-facts-all-your-product-are-belong-to-us)). They're very open to outside ideas and contributions, for example as part of the Google Summer of Code and stuff like that.
> 
> Wikidata would also be a good option -- in fact anything would be better that starting yet another project IMHO. wink

thanks for this link! yes i agree, it will be much better to build upon things that have already been done and collaborate with existing initiatives. Would you be happy to help brainstorm in the future about how exactly the project should take shape?

**Comment by johanricher** [comment]
@Rik44444 Of course! Where should that discussion take place?

To continue on the idea to use OpenFoodFacts, it might be useful to start listing the things that are missing there in order to accomplish the goals (i.e. user stories) that you envision for your project?

In that case, I would recommend opening an issue on https://github.com/openfoodfacts/openfoodfacts-server/ or starting a discussion [on their Slack](https://slack.openfoodfacts.org/).

**Comment by Rik44444** [comment]
> 
> 
> @Rik44444 Of course! Where should that discussion take place?
> 
> To continue on the idea to use OpenFoodFacts, it might be useful to start listing the things that are missing there in order to accomplish the goals (i.e. user stories) that you envision for your project?
> 
> In that case, I would recommend opening an issue on https://github.com/openfoodfacts/openfoodfacts-server/ or starting a discussion [on their Slack](https://slack.openfoodfacts.org/).

great! i'll think about it, i think i'll start a separate forum for this so we can all discuss it collaboratively. May take me some time thought to get it started ; i'll let you know when it's up and running!

**Comment by Rik44444** [comment]
@johanricher i posted something [here](https://www.wikidata.org/wiki/Wikidata:Project_chat#giving_consumers_better_opportunities_for_making_informed_decisions_about_which_products_and_services_to_consume), to also ask the Wikidata for their input. Would be great if you could give your views as well!

**Comment by ferrisoxide** [comment]
Hey @Rik44444 @johanricher et al, I've some thoughts here vis-a-vis sharing data between open product data sources - something along the lines of the use cases covered by GS1's [Global Data Synchronization Network](https://en.wikipedia.org/wiki/Global_Data_Synchronization_Network) standards.

Nutshell idea is to identify protocols for subscribing and publishing product data between open systems. Not sure where it'd a good forum for discussing this kind of stuff, but if anyone is keen to pursue this sort of stuff - or is already engaged in those kinds of discussions - I'd be interested in being involved.

**Comment by Rik44444** [comment]
> 
> 
> Hey @Rik44444 @johanricher et al, I've some thoughts here vis-a-vis sharing data between open product data sources - something along the lines of the use cases covered by GS1's [Global Data Synchronization Network](https://en.wikipedia.org/wiki/Global_Data_Synchronization_Network) standards.
> 
> Nutshell idea is to identify protocols for subscribing and publishing product data between open systems. Not sure where it'd a good forum for discussing this kind of stuff, but if anyone is keen to pursue this sort of stuff - or is already engaged in those kinds of discussions - I'd be interested in being involved.

hi @ferrisoxide , that's great! my post on the Wiki Chat has movedi see, it's now [here ](https://www.wikidata.org/wiki/Wikidata:Project_chat/Archive/2020/02#giving_consumers_better_opportunities_for_making_informed_decisions_about_which_products_and_services_to_consume). Feel free to add to the wiki there! Happy to collaborate on this.

**Comment by ferrisoxide** [comment]
Hey @Rik44444 

Cool. Excellent to connect on this.

I noticed you've flagged Datakick as a dead link. I mentioned this in #16, that I'd stood up a service at https://www.brocade.io - funnily enough this is actually intended as a Datakick replacement. It was seeded originally using data from Datakick and the API is compatible with Datakick's (read-only for now).

I'm a bit clueless as to how to engage in the Wiki Chat. Will have a look in the morning when I'm a little more awake :)

**Comment by Rik44444** [comment]
no worries, we can setup a separate forum for this, if you'd like! would you like to do it, on brocade.io, or shall i try to set one up on one of my domains?

**Comment by Rik44444** [comment]
i wonder if there are open data standards for products in general

**Comment by ferrisoxide** [comment]
@Rik44444 GS1 formalise a bunch of things (https://www.gs1.org/standards). I've only dipped my toe in this, so still very much learning.

I'll get my head around how to use Wiki Chat - or we can set up a forum somewhere. Not super stressed right now - more interested in sleep :) Feel free to DM or send an email if you want to take this out of the channel here.

**Comment by avdata99** [comment]
This repository has been archived due to inactivity. See #16 for alternatives
