### ISSUE TITLE
I tried to use the website and crashed it.

### ISSUE THREAD

**Issue by jrddunbr** [okfn/labs-opd#6]
I was using a bar-code reader (for fun) and tried it on the search box with an ESBN (I think) from the back of a book. Specifically, `058489720300299500000017`

It proceeded to crash. Attached, find the HTML document that resulted (since GitHub doesn't like raw HTML apparently)

`DEBUG=True` in the django settings managed to output what may be some useful information. May not be the best thing to have on a live website though.

[DataError.html.zip](https://github.com/okfn/labs-opd/files/2426681/DataError.html.zip)

**Comment by avdata99** [comment]
This repository has been archived due to inactivity. See #16 for alternatives
